---
language: python

services: docker

branches:
    only:
        - master
        - /^v?\d+\.\d+\.\d+(-\S*)?$/

env:
    global:
        - ROLE_NAME=xtrabackup
    matrix:
        - MOLECULE_DISTRO=ubuntu1604 SCENARIO=default
        - MOLECULE_DISTRO=ubuntu1804 SCENARIO=default
        - MOLECULE_DISTRO=debian8 SCENARIO=default
        - MOLECULE_DISTRO=debian9 SCENARIO=default
        - MOLECULE_DISTRO=centos7 SCENARIO=default
        - MOLECULE_DISTRO=ubuntu1604 SCENARIO=all
        - MOLECULE_DISTRO=ubuntu1804 SCENARIO=all
        - MOLECULE_DISTRO=debian8 SCENARIO=all
        - MOLECULE_DISTRO=debian9 SCENARIO=all
        - MOLECULE_DISTRO=centos7 SCENARIO=all

install: pip install -r requirements.txt -c constraints.txt

# Use actual Ansible Galaxy role name for the project directory
before_script:
    - cd ../
    - mv ansible-role-$ROLE_NAME $ROLE_NAME
    - cd $ROLE_NAME

script: molecule test

notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/
