---
- name: Set vars for OS family
  include_vars: "{{ ansible_os_family }}.yml"

- import_tasks: repository.yml

- import_tasks: install.yml

- import_tasks: system_user.yml
  when: xtrabackup_create_system_user

- import_tasks: mysql_user.yml
  when: xtrabackup_create_mysql_user
