---
- name: Converge
  hosts: all
  pre_tasks:
    - name: This likely fixes stale apt caches in Docker images
      apt:
        update_cache: true
        cache_valid_time: 3600
      when:
        - ansible_os_family == 'Debian'
  roles:
    - role: xtrabackup
